-- TABELAS PARA GAMES NOSTALGICOS

CREATE TABLE IF NOT EXISTS public.app_state (
  key text PRIMARY KEY,
  value jsonb
);

CREATE TABLE IF NOT EXISTS public.games (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text,
  platform text,
  console_slug text,
  price numeric,
  download_link text,
  status text,
  is_hot boolean,
  image text,
  highlight_color text,
  badge text,
  badge_color text,
  video_id text,
  category text,
  description text,
  size text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.consoles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  slug text,
  status text,
  image text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  email text,
  password_hash text,
  role text,
  status text,
  registered_at text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.pedidos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number text,
  client_email text,
  client_info jsonb,
  date text,
  total numeric,
  status text,
  has_unread_cliente boolean DEFAULT false,
  has_unread_admin boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.pedido_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id bigint REFERENCES public.pedidos(id) ON DELETE CASCADE,
  name text,
  qty integer,
  price numeric
);

CREATE TABLE IF NOT EXISTS public.pedido_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id bigint REFERENCES public.pedidos(id) ON DELETE CASCADE,
  sender text,
  text text,
  timestamp text,
  "isAdmin" boolean
);

CREATE TABLE IF NOT EXISTS public.solicitacoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email text,
  game_name text,
  console text,
  notes text,
  status text,
  created_at timestamp with time zone DEFAULT now()
);

-- Permissões abertas temporárias para podermos migrar os dados
ALTER TABLE public.app_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.games ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consoles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedido_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedido_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.solicitacoes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow All" ON public.app_state FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All" ON public.games FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All" ON public.consoles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All" ON public.users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All" ON public.pedidos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All" ON public.pedido_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All" ON public.pedido_messages FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All" ON public.solicitacoes FOR ALL USING (true) WITH CHECK (true);
